-- 1. 직원명단 테이블 생성 (사원번호, 이름, 부서, 나이)
CREATE TABLE EMPLOYEE( 
    EMPLOYEE_NUM VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    DEPARTMENT VARCHAR2(20) NOT NULL,
    AGE INT
);

-- 2. 부서명단 테이블 생성 (부서번호, 부서이름, 직원수)
CREATE TABLE DEPARTMENT(
    DEPARTMENT_NUM VARCHAR2(20) PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(20) NOT NULL,
    EMPLOYEES INT 
);

-- 3. 직원명단 테이블에 대해서 데이터 추가
INSERT INTO EMPLOYEE VALUES ('521', '김길동', '경영행정부', 25);
INSERT INTO EMPLOYEE VALUES ('525', '이길동', '교무부', 40);
INSERT INTO EMPLOYEE VALUES ('523', '최길동', '교무부', 30);
INSERT INTO EMPLOYEE VALUES ('524', '정길동', '교무지원부', 29);

-- 4. 부서명단 테이블에 대해서 데이터 추가
INSERT INTO DEPARTMENT VALUES ('1', '교무부', 30);
INSERT INTO DEPARTMENT VALUES ('2', '교무지원부', 15);
INSERT INTO DEPARTMENT VALUES ('3', '경영행정부', 10);

-- 5. 직원명단과 부서명단 테이블의 모든 데이터를 출력
SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;

-- 6. 직원명단 테이블에 대해서, NAME, DEPARTMENT 칼럼에 대한 정보만 출력
SELECT NAME, DEPARTMENT FROM EMPLOYEE;

-- 7. 직원명단 테이블에 대해서, 부서가 교무부인 데이터만 검색하여 EMPLOYEE_NUM, NAME, DEPARTMENT 정보만 출력
SELECT EMPLOYEE_NUM, NAME, DEPARTMENT FROM EMPLOYEE WHERE DEPARTMENT = '교무부';

-- 8. 부서명단 테이블에 대해서, 직원수가 10명 초과인 데이터만 검색하여 DEPARTMENT_NAME, EMPLOYEES 정보만 출력
SELECT DEPARTMENT_NAME, EMPLOYEES FROM DEPARTMENT WHERE EMPLOYEES > 10;

-- 9. 부서명단 테이블에 대해서, 부서번호가 2인 데이터만 검색하여 전체 칼럼의 정보를 출력
SELECT * FROM DEPARTMENT WHERE DEPARTMENT_NUM = '2';

-- 10. 직원명단과 부서명단 테이블을 삭제
DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;

COMMIT;